# Generated by Django 4.2.6 on 2024-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Список категорий'},
        ),
        migrations.AddField(
            model_name='category',
            name='alternative',
            field=models.CharField(max_length=255, null=True, verbose_name='Версия на испанском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Английское название для мультиязычности', max_length=64, verbose_name='Имя'),
        ),
    ]
