# Generated by Django 4.2.6 on 2024-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0003_alter_category_options_category_alternative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Английское название для мультиязычности', max_length=64, verbose_name='Версия на английском'),
        ),
    ]
