# Generated by Django 4.2.6 on 2024-10-08 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stc', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('photo', models.ImageField(null=True, upload_to='images/blog', verbose_name='Фотография статьи')),
                ('text', models.CharField(verbose_name='Текст статьи')),
                ('language', models.CharField(choices=[('en', 'Английский'), ('es', 'Испанский'), ('ru', 'Русский')], max_length=64, verbose_name='Язык статьи')),
                ('link', models.CharField(help_text='Английское название без пробелов и дефисов, только нижнее подчёркивание', max_length=255, verbose_name='Ссылка на статью')),
                ('datetime', models.DateTimeField(verbose_name='Дата создания')),
                ('is_public', models.BooleanField(verbose_name='Статус публикации')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='stc.category', verbose_name='Категория статьи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
        ),
    ]
