# Generated by Django 4.2.6 on 2024-10-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0005_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('robots', models.CharField(choices=[('index, follow', 'Индексировать текст страницы. Переходить по ссылкам на странице.'), ('index, nofollow', 'Индексировать текст страницы. Не переходить по ссылкам на странице.'), ('noindex, follow', 'Не индексировать текст страницы. Переходить по ссылкам на странице.'), ('noindex, nofollow', 'Не индексировать текст страницы. Не переходить по ссылкам на странице.')], default='index, follow', max_length=255, verbose_name='Метатег robots')),
                ('type', models.CharField(default='website', max_length=64, verbose_name='Тип страницы')),
                ('image', models.CharField(max_length=255, null=True, verbose_name='Картинка страницы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('description', models.CharField(max_length=200, verbose_name='Описание страницы')),
                ('keywords', models.CharField(help_text='Слова в единственном числе, через запятую, которые встречаются в тексте, не более 200 символов.', max_length=200, null=True, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO-оптимизация',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'статью', 'verbose_name_plural': 'Список статей'},
        ),
    ]
