# Generated by Django 4.2.6 on 2024-10-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0006_seoblock_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='stc.articles', verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='type',
            field=models.CharField(choices=[('website', 'Веб-сайт'), ('article', 'Статья'), ('book', 'Книга'), ('profile', 'Профиль'), ('music', 'Музыка или аудио'), ('video', 'Видео или фильм')], default='website', max_length=64, verbose_name='Тип страницы'),
        ),
    ]
