# Generated by Django 4.2.6 on 2024-10-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0007_alter_seoblock_title_alter_seoblock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='image',
            field=models.CharField(null=True, verbose_name='Картинка страницы'),
        ),
    ]
