# Generated by Django 4.2.6 on 2024-10-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0008_alter_seoblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='stc.articles', verbose_name='Заголовок страницы'),
        ),
    ]
