# Generated by Django 4.2.6 on 2024-10-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0009_alter_seoblock_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='stc.seoblock', verbose_name='Meta-теги'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='title',
            field=models.CharField(verbose_name='Заголовок страницы'),
        ),
    ]
