# Generated by Django 4.2.6 on 2024-10-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0010_articles_seo_alter_seoblock_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to='images/blog', verbose_name='Фотография статьи'),
        ),
    ]
