# Generated by Django 4.2.6 on 2024-10-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0011_alter_articles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Картинка страницы'),
        ),
    ]
