# Generated by Django 4.2.6 on 2024-10-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0012_alter_seoblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание страницы'),
        ),
    ]
