# Generated by Django 4.2.6 on 2024-10-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0013_alter_seoblock_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='keywords',
            field=models.CharField(help_text='Слова в единственном числе, через запятую, которые встречаются в тексте, не более 200 символов.', max_length=255, null=True, verbose_name='Ключевые слова'),
        ),
    ]
