# Generated by Django 4.2.6 on 2024-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0014_alter_seoblock_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание страницы'),
        ),
    ]
