# Generated by Django 4.2.6 on 2024-11-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0016_profiles_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(max_length=255, upload_to='images/users', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='href',
            field=models.CharField(default='id001731005987.40256', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
