# Generated by Django 4.2.6 on 2024-11-07 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stc', '0017_alter_profiles_avatar_alter_profiles_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(max_length=255, upload_to='images/users', verbose_name='Фотография')),
                ('account', models.CharField(max_length=255, null=True, verbose_name='Аккаунт')),
                ('contact', models.CharField(max_length=255, null=True, verbose_name='Контакты')),
                ('background', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/users/bg', verbose_name='Фон')),
                ('href', models.CharField(default='id001731006985.617414', max_length=255, verbose_name='Юзернейм')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
