# Generated by Django 4.2.6 on 2024-11-07 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stc', '0018_profile_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731011853.393688', max_length=255, verbose_name='Юзернейм'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=64, verbose_name='Текущая валюта')),
                ('name', models.CharField(choices=[('Start', 'Start'), ('Business', 'Business'), ('Free', 'Free')], default='Free', max_length=255, verbose_name='Название тарифа')),
                ('due_date', models.CharField(choices=[('1', '1 месяц'), ('3', '3 месяца'), ('6', '6 месяцев'), ('12', '1 год')], default='3', max_length=255, verbose_name='Срок оплаты')),
                ('is_payment', models.BooleanField(verbose_name='Статус оплаты')),
                ('datetime', models.DateTimeField(verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'Список аккаунтов',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='stc.account'),
        ),
    ]
