# Generated by Django 4.2.6 on 2024-11-08 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stc', '0019_alter_profile_href_account_alter_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731104900.611079', max_length=255, verbose_name='Юзернейм'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('YouTube', 'YouTube'), ('Rutube', 'Rutube'), ('TikTok', 'TikTok'), ('Vk', 'Vk'), ('Dzen', 'Dzen'), ('Telegram', 'Telegram'), ('TenChat', 'TenChat'), ('Threads', 'Threads'), ('Vc', 'Vc'), ('Instagram', 'Instagram'), ('Site', 'сайт'), ('Email', 'e-mail'), ('Phone', 'телефон')], max_length=255, verbose_name='Тип контакта')),
                ('is_public', models.BooleanField(verbose_name='Публичный')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на ресурс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='stc.contact'),
        ),
    ]
