# Generated by Django 4.2.6 on 2024-11-09 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0020_alter_profile_href_contact_alter_profile_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакты', 'verbose_name_plural': 'Список контактов'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='stc.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731112649.130506', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
