# Generated by Django 4.2.6 on 2024-11-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0021_alter_contact_options_remove_profile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731112737.584399', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
