# Generated by Django 4.2.6 on 2024-11-09 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stc', '0022_alter_profile_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='stc.profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731112991.898814', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
