# Generated by Django 4.2.6 on 2024-11-09 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0023_alter_contact_profile_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='stc.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731113521.308209', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
