# Generated by Django 4.2.6 on 2024-11-09 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0024_alter_contact_profile_alter_profile_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='stc.contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731113590.237881', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
