# Generated by Django 4.2.6 on 2024-11-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0027_alter_contact_profile_alter_profile_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001731114293.005616', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
