# Generated by Django 4.2.6 on 2025-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0029_alter_profile_href_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_position', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Список данных',
            },
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'сессии', 'verbose_name_plural': 'Сессии пользователей'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001738935596', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
