# Generated by Django 4.2.6 on 2025-02-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0030_note_alter_userlogin_options_alter_profile_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='stc.profile'),
        ),
        migrations.AlterField(
            model_name='note',
            name='language',
            field=models.CharField(choices=[('en', 'Английский'), ('es', 'Испанский'), ('ru', 'Русский')], max_length=64, verbose_name='Язык заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='stc.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001738936193', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
