# Generated by Django 4.2.6 on 2025-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0031_alter_contact_profile_alter_note_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(verbose_name='Описание о себе'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user_position',
            field=models.CharField(max_length=255, verbose_name='Должность / Специальность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001738936516', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
