# Generated by Django 4.2.6 on 2025-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0032_alter_note_description_alter_note_user_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='summa',
            field=models.CharField(default=0, max_length=255, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001738947890', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
