# Generated by Django 4.2.6 on 2025-02-07 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stc', '0033_account_summa_alter_profile_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001738966431', max_length=255, verbose_name='Юзернейм'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Start', 'Start'), ('Business', 'Business'), ('Free', 'Free')], default='Free', max_length=255, verbose_name='Название тарифа')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('payment', models.CharField(blank=True, max_length=255, null=True, verbose_name='№ платежа')),
                ('status', models.CharField(choices=[('pending', 'Ожидание оплаты'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Список транзакций',
            },
        ),
    ]
