# Generated by Django 4.2.6 on 2025-02-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0034_alter_profile_href_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='', max_length=64, verbose_name='Текущая валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='href',
            field=models.CharField(default='id001738968905', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
